version: '3.8'
services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next-cache:/app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://myuser:mypassword@db:3306/mydatabase
    command: >
      sh -c "
             if [ ! -d node_modules ]; then
             echo 'Installing dependencies...' &&
             npm install &&
             npm install next@latest;
             fi &&
             echo 'Starting development server...' &&
             npx next dev"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      - db

volumes:
  node_modules:
  next-cache:
  mysql_data:
