services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5555:5555"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - next-cache:/app/.next
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://myuser:mypassword@db:3306/mydatabase
      NEXTAUTH_SECRET: 1162e2bd67bd6e558dc59e4aa23f6630831f6752145352cf8504ea8db5f77228
      NEXTAUTH_URL: http://localhost:3000
      STRIPE_SECRET_KEY: sk_test_51QqdlPDBg9iVvqAELxZJiU2fzRBbPQ1kBMSxSYR3fo1MGbZDakhOqhoLVaZGu4v0v2M2KC806rC5F9ALq6k5Cr1700ApHInZot
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_51QqdlPDBg9iVvqAEcNyRspRoAIYwqdigK7DCluqw0UUgXedpc54Zm9KawStRlNVDcwI4BWXGF6fqgJ4zNLL9HBpj00qyuGg3sp
      STRIPE_WEBHOOK_SECRET: whsec_06e2d3c77ba397029370a9672bfd8086b566dd4632c64af8468a0a6775295b74
      MAILJET_API_PUBLIC_KEY: 8a2a8c3f25e95bf4824c2571570df840
      MAILJET_API_PRIVATE_KEY: bf53401d0b45f0a47db803b03a42294c
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  next-cache:
  mysql_data:
