# Utiliser une image officielle de Node.js comme base
FROM node:18-alpine

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code de l'application dans le conteneur
COPY . .

# Exposer le port 3000 (ou le port que Next.js utilise)
EXPOSE 3000

# Commande pour lancer l'application Next.js
CMD ["npm", "run", "dev"]
