services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next-cache:/app/.next
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    command: >
      sh -c "
             if [ ! -d node_modules ]; then
             echo 'Installing dependencies...' &&
             npm install &&
             npm install next@latest;
             fi &&
             echo 'Starting development server...' &&
             npx next dev"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules:
  next-cache:
  postgres_data: