services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5555:5555"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - next-cache:/app/.next
    environment:
      NODE_ENV: development
      DATABASE_URL: DATABASE_URL
      NEXTAUTH_SECRET: NEXTAUTH_SECRET
      NEXTAUTH_URL: http://localhost:3000
      STRIPE_SECRET_KEY: STRIPE_SECRET_KEY
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      STRIPE_WEBHOOK_SECRET: STRIPE_WEBHOOK_SECRET
      MAILJET_API_PUBLIC_KEY: MAILJET_API_PUBLIC_KEY
      MAILJET_API_PRIVATE_KEY: MAILJET_API_PRIVATE_KEY
      NEXT_PUBLIC_SUPABASE_URL: NEXT_PUBLIC_SUPABASE_URL
      NEXT_PUBLIC_SUPABASE_KEY: NEXT_PUBLIC_SUPABASE_KEY
    command: >
      sh -c "
        npm install &&
        npm run dev
      "
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  next-cache:
  mysql_data:
