name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/nextjs-app:${{ github.sha }} .
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image as latest
        run: |
          docker tag ghcr.io/${{ github.repository }}/nextjs-app:${{ github.sha }} ghcr.io/${{ github.repository }}/nextjs-app:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository }}/nextjs-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/nextjs-app:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/food-drive-group-3/drive-express
            docker-compose pull nextjs
            docker-compose up -d
            docker-compose exec nextjs npm run migrate
